/**
 * Job: Send queued emails.
 * Processes pending emails from the queue and sends them via the configured provider.
 * Called by daily cron job (api/cron/tick).
 *
 * Handles:
 * - Fetching pending emails
 * - Rendering templates
 * - Sending via SMTP/Resend
 * - Retry logic for failed sends
 * - Cleanup of old processed emails
 */

import {
  getPendingEmails,
  markEmailSent,
  markEmailFailed,
  cleanupOldEmails,
  retryFailedEmails,
} from "../email-templates/queue";
import type { EmailQueueItem } from "../email-templates/types";
import { sendMail } from "../mailer";
import { renderTemplate } from "../email-templates/renderer";

// Template component imports
import { WelcomeNewUserTemplate } from "../email-templates/welcome-template";
import { WelcomeNewWorkspaceTemplate } from "../email-templates/welcome-template";
import {
  ChapterSubmissionNotification,
  ChapterApprovedNotification,
  ChapterRevisionRequestedNotification,
} from "../email-templates/chapter-notifications-template";
import {
  CoachMessageNotification,
  WeeklyCoachDigest,
  CohortSessionReminder,
  CoachingReminder,
} from "../email-templates/coaching-templates";
import {
  MilestoneAchieved,
  JourneyProgress,
  GrowthPlanUpdate,
  TransformationReportReady,
} from "../email-templates/milestone-templates";

const BATCH_SIZE = 50;
const MAX_RETRIES = 3;

export interface SendEmailJobResult {
  processed: number;
  sent: number;
  failed: number;
  errors: Array<{ emailId: string; error: string }>;
}

/**
 * Process and send queued emails.
 */
export async function processSendQueuedEmails(): Promise<SendEmailJobResult> {
  const result: SendEmailJobResult = {
    processed: 0,
    sent: 0,
    failed: 0,
    errors: [],
  };

  try {
    // Process pending emails in batches
    let batch = await getPendingEmails(BATCH_SIZE);

    while (batch.length > 0) {
      for (const queuedEmail of batch) {
        result.processed++;

        try {
          // Render the email
          const { html, subject } = await renderQueuedEmail(queuedEmail);

          // Send the email
          const sendResult = await sendMail({
            to: queuedEmail.to,
            subject,
            text: "", // Plain text will be generated by mailer from HTML
            html,
          });

          if (sendResult.sent) {
            await markEmailSent(queuedEmail.id);
            result.sent++;
          } else {
            await markEmailFailed(queuedEmail.id, sendResult.reason || "Unknown error", MAX_RETRIES);
            result.failed++;
            result.errors.push({
              emailId: queuedEmail.id,
              error: sendResult.reason || "Send failed",
            });
          }
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : "Unknown error";
          await markEmailFailed(queuedEmail.id, errorMsg, MAX_RETRIES);
          result.failed++;
          result.errors.push({
            emailId: queuedEmail.id,
            error: errorMsg,
          });
        }
      }

      // Fetch next batch
      batch = await getPendingEmails(BATCH_SIZE);
    }

    // Retry previously failed emails that haven't exceeded max retries
    console.log("[email-job] Attempting to retry failed emails...");
    await retryFailedEmails(MAX_RETRIES);

    // Clean up old processed emails (30-day retention)
    const cleaned = await cleanupOldEmails(30);
    console.log(`[email-job] Cleaned up ${cleaned} old email records`);
  } catch (error) {
    console.error("[email-job] Fatal error:", error);
  }

  console.log(
    `[email-job] Completed: ${result.processed} processed, ${result.sent} sent, ${result.failed} failed`,
  );

  return result;
}

/**
 * Render a queued email based on its template ID and data.
 */
async function renderQueuedEmail(
  queuedEmail: EmailQueueItem,
): Promise<{ html: string; subject: string }> {
  const { templateId, data } = queuedEmail;

  // Type-safe template rendering
  let component: React.ReactNode;
  let subject: string;

  switch (templateId) {
    case "welcome-user":
      component = (
        <WelcomeNewUserTemplate
          name={String(data.name || "User")}
          verificationLink={String(data.verificationLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = "Welcome to ONEVYRT!";
      break;

    case "welcome-workspace":
      component = (
        <WelcomeNewWorkspaceTemplate
          businessName={String(data.businessName || "")}
          workspaceName={String(data.workspaceName || "")}
          ownerName={String(data.ownerName || "")}
          inviteLink={String(data.inviteLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = "Your New Workspace is Ready";
      break;

    case "chapter-submission":
      component = (
        <ChapterSubmissionNotification
          learnerName={String(data.learnerName || "")}
          chapterNumber={Number(data.chapterNumber || 1)}
          chapterName={String(data.chapterName || "")}
          submissionDate={String(data.submissionDate || new Date().toLocaleDateString())}
          viewLink={String(data.viewLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = `New Chapter Submission - ${data.chapterName}`;
      break;

    case "chapter-approved":
      component = (
        <ChapterApprovedNotification
          learnerName={String(data.learnerName || "")}
          coachName={String(data.coachName || "")}
          chapterNumber={Number(data.chapterNumber || 1)}
          chapterName={String(data.chapterName || "")}
          nextChapterNumber={data.nextChapterNumber ? Number(data.nextChapterNumber) : undefined}
          nextChapterName={data.nextChapterName ? String(data.nextChapterName) : undefined}
          feedbackHighlights={Array.isArray(data.feedbackHighlights) ? (data.feedbackHighlights as string[]) : []}
          continueLink={String(data.continueLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = `Chapter Approved - ${data.chapterName}`;
      break;

    case "chapter-revision":
      component = (
        <ChapterRevisionRequestedNotification
          learnerName={String(data.learnerName || "")}
          coachName={String(data.coachName || "")}
          chapterNumber={Number(data.chapterNumber || 1)}
          chapterName={String(data.chapterName || "")}
          revisionReason={String(data.revisionReason || "")}
          revisionDeadline={data.revisionDeadline ? String(data.revisionDeadline) : undefined}
          reviseLink={String(data.reviseLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = `Revision Requested - ${data.chapterName}`;
      break;

    case "coach-message":
      component = (
        <CoachMessageNotification
          learnerName={String(data.learnerName || "")}
          coachName={String(data.coachName || "")}
          subject={String(data.subject || "")}
          messagePreview={String(data.messagePreview || "")}
          viewLink={String(data.viewLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = `Message from ${data.coachName}`;
      break;

    case "coach-weekly-digest":
      component = (
        <WeeklyCoachDigest
          coachName={String(data.coachName || "")}
          weekNumber={Number(data.weekNumber || 1)}
          quietLearners={Array.isArray(data.quietLearners) ? (data.quietLearners as { name: string; chapterStatus: string; daysQuiet: number }[]) : []}
          pendingReviews={Number(data.pendingReviews || 0)}
          recentlyCompleted={Number(data.recentlyCompleted || 0)}
          coachPortalLink={String(data.coachPortalLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = `Weekly Coaching Digest - Week ${data.weekNumber}`;
      break;

    case "cohort-session-reminder":
      component = (
        <CohortSessionReminder
          learnerName={String(data.learnerName || "")}
          coachName={String(data.coachName || "")}
          sessionDate={String(data.sessionDate || "")}
          sessionTime={String(data.sessionTime || "")}
          sessionTopic={String(data.sessionTopic || "")}
          joinLink={String(data.joinLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
          hoursUntilSession={Number(data.hoursUntilSession || 24)}
        />
      );
      subject = "Cohort Session Reminder";
      break;

    case "coaching-reminder":
      component = (
        <CoachingReminder
          learnerName={String(data.learnerName || "")}
          reminderType={data.reminderType as "stalled" | "incomplete" | "upcoming-deadline"}
          chapterNumber={data.chapterNumber ? Number(data.chapterNumber) : undefined}
          chapterName={data.chapterName ? String(data.chapterName) : undefined}
          actionUrl={String(data.actionUrl || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = "Keep Your Momentum Going";
      break;

    case "milestone-achieved":
      component = (
        <MilestoneAchieved
          learnerName={String(data.learnerName || "")}
          milestoneType={
            data.milestoneType as
              | "first-chapter-complete"
              | "all-chapters-complete"
              | "first-assignment"
              | "halfway-through"
          }
          milestoneTitle={String(data.milestoneTitle || "")}
          milestoneDescription={String(data.milestoneDescription || "")}
          nextStepLink={String(data.nextStepLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = "You've Achieved a Milestone!";
      break;

    case "journey-progress":
      component = (
        <JourneyProgress
          learnerName={String(data.learnerName || "")}
          currentChapter={Number(data.currentChapter || 1)}
          totalChapters={Number(data.totalChapters || 4)}
          completedChapters={Number(data.completedChapters || 0)}
          currentFocus={String(data.currentFocus || "")}
          dashboardLink={String(data.dashboardLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = "Your Programme Progress Update";
      break;

    case "growth-plan-update":
      component = (
        <GrowthPlanUpdate
          learnerName={String(data.learnerName || "")}
          coachName={String(data.coachName || "")}
          bottleneckIdentified={String(data.bottleneckIdentified || "")}
          improvementAreas={Array.isArray(data.improvementAreas) ? (data.improvementAreas as string[]) : []}
          timelineMonths={Number(data.timelineMonths || 3)}
          viewPlanLink={String(data.viewPlanLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = "Your Growth Plan is Ready";
      break;

    case "transformation-report-ready":
      component = (
        <TransformationReportReady
          learnerName={String(data.learnerName || "")}
          reportLink={String(data.reportLink || "")}
          shareLink={String(data.shareLink || "")}
          downloadPdfLink={String(data.downloadPdfLink || "")}
          appUrl={String(data.appUrl || "https://onevyrt.masteryresearch.com")}
        />
      );
      subject = "Your Transformation Report is Ready";
      break;

    default:
      throw new Error(`Unknown template: ${templateId}`);
  }

  const rendered = await renderTemplate(component, subject);
  return { html: rendered.html, subject: rendered.subject };
}
