// Industry starter templates — one proven flow per business domain, so the
// library covers 15+ distinct industries.
import type { CampaignTemplate } from "./types";

export const INDUSTRY_TEMPLATES: CampaignTemplate[] = [
  {
    id: "ecommerce-launch",
    name: "E-commerce Product Drop",
    category: "E-commerce",
    description: "Launch a new product or collection to an existing audience and paid traffic in one coordinated push.",
    objective: "Sell through a new drop fast and build a waitlist for the next one.",
    channel: "Meta + Email",
    steps: [
      { channel: "email", kind: "email", day: -3, title: "Early-access waitlist", content: "Tell your list a drop is coming and offer early access in exchange for joining the waitlist. Tease the product, not the price." },
      { channel: "meta", kind: "ad", day: 0, title: "Launch ad", content: "Show the product in use, lead with the one thing that makes it different, and send to the product page. Retarget site visitors first." },
      { channel: "email", kind: "email", day: 0, title: "It's live", content: "Announce the drop to the waitlist first. Strong product photography, the core benefit, and a single buy button." },
      { channel: "email", kind: "email", day: 2, title: "Bestseller / low stock", content: "Social-proof the launch: what's selling, sizes/variants running low. Honest scarcity only, one CTA." },
    ],
  },
  {
    id: "saas-trial-activation",
    name: "SaaS Trial Activation",
    category: "SaaS",
    description: "Turn free signups into activated users who reach value before the trial ends.",
    objective: "Drive trial-to-paid conversion by getting users to their 'aha' moment fast.",
    channel: "Email + In-app",
    steps: [
      { channel: "email", kind: "email", day: 0, title: "Set up in 5 minutes", content: "Welcome the signup and guide them to the single setup step that unlocks the core value. One link, one outcome." },
      { channel: "email", kind: "email", day: 2, title: "Do this next", content: "Point to the next high-value action once they're set up. Show the result they'll get, not a feature tour." },
      { channel: "email", kind: "email", day: 5, title: "How teams use it", content: "Share a concrete workflow or short case so they see the product fitting their own work." },
      { channel: "email", kind: "email", day: 7, title: "Trial ending — upgrade", content: "Recap the value they've built, make upgrading one click, and offer to help if they're stuck." },
    ],
  },
  {
    id: "coaching-highticket",
    name: "Coaching / Consulting (High-Ticket)",
    category: "Coaching",
    description: "Move a warm audience toward a booked discovery call for a premium coaching or consulting offer.",
    objective: "Book qualified discovery calls and convert them into high-ticket clients.",
    channel: "Email + Organic",
    steps: [
      { channel: "organic", kind: "post", day: 0, title: "Authority post", content: "Share a real client outcome or a contrarian insight from your work. Establish the specific transformation you deliver." },
      { channel: "email", kind: "email", day: 1, title: "Case study", content: "Walk through one client's before → after in detail. Focus on the problem, the shift, and the result — not your methodology." },
      { channel: "email", kind: "email", day: 3, title: "Invitation to a call", content: "Invite the right-fit person to a no-pressure discovery call. Be clear who it's for and who it isn't. One booking link." },
      { channel: "email", kind: "email", day: 6, title: "Objection + reminder", content: "Address the biggest reason people hesitate on a call (time, price, readiness) and re-offer the booking link." },
    ],
  },
  {
    id: "realestate-listings",
    name: "Real Estate — New Listing",
    category: "Real estate",
    description: "Promote a new listing to buyers and build a pipeline of seller leads in the area.",
    objective: "Fill viewings for a listing and capture new seller and buyer leads locally.",
    channel: "Meta + Email + SMS",
    steps: [
      { channel: "meta", kind: "ad", day: 0, title: "Listing showcase ad", content: "Geo-targeted ad with the best photos, the neighbourhood, price and one standout feature. Link to a viewing booking page." },
      { channel: "landing", kind: "landing", day: 0, title: "Listing + book a viewing", content: "Photo gallery, key facts, map, and a simple 'book a viewing' form. Capture phone and email." },
      { channel: "sms", kind: "sms", day: 1, title: "Viewing confirmation", content: "Confirm the viewing time and address, add a reschedule link. Keep it short." },
      { channel: "email", kind: "email", day: 3, title: "Similar homes + valuation", content: "For non-bookers: send similar listings and offer a free home valuation to surface seller leads." },
    ],
  },
  {
    id: "restaurant-offer",
    name: "Restaurant / Café Promotion",
    category: "Hospitality",
    description: "Drive covers on quiet nights and grow a repeat-visit list with a local offer.",
    objective: "Fill tables midweek and build a list of regulars you can bring back.",
    channel: "Meta + SMS",
    steps: [
      { channel: "meta", kind: "ad", day: 0, title: "Midweek offer ad", content: "Geo-targeted ad with a specific midweek offer and mouth-watering photography. Lead with the neighbourhood and the deal." },
      { channel: "landing", kind: "landing", day: 0, title: "Claim / book a table", content: "Simple page: the offer, the menu highlight, hours, map, and a booking button. Capture phone for the reminder." },
      { channel: "sms", kind: "sms", day: 1, title: "Booking reminder", content: "Confirm the reservation, restate the offer, add directions. One short message." },
      { channel: "email", kind: "email", day: 7, title: "Come back", content: "After the visit, thank them and invite them back with a reason — a new dish, an event, or a loyalty perk." },
    ],
  },
  {
    id: "fitness-challenge",
    name: "Fitness Studio / Gym Challenge",
    category: "Fitness",
    description: "Fill a class or a time-boxed challenge, then convert trial members into memberships.",
    objective: "Sign up challenge participants and convert them to paying members.",
    channel: "Meta + Email + SMS",
    steps: [
      { channel: "meta", kind: "ad", day: -7, title: "Challenge ad", content: "Promote a specific, time-boxed challenge (e.g. a 6-week result). Lead with the outcome and who it's for. Local targeting." },
      { channel: "landing", kind: "landing", day: -7, title: "Challenge signup", content: "One promise, what's included, the start date, and a simple signup with payment or a free-trial capture." },
      { channel: "sms", kind: "sms", day: 0, title: "Day 1 kickoff", content: "Welcome them, confirm class time and what to bring. Build momentum for the first session." },
      { channel: "email", kind: "email", day: 5, title: "Convert to membership", content: "Celebrate early wins and offer a member rate to continue after the challenge. Clear deadline and CTA." },
    ],
  },
  {
    id: "dental-recall",
    name: "Dental / Medical Practice",
    category: "Healthcare",
    description: "Bring lapsed patients back for check-ups and promote a specific treatment ethically.",
    objective: "Fill the appointment book with recalls and qualified new-patient enquiries.",
    channel: "Email + SMS",
    steps: [
      { channel: "meta", kind: "ad", day: 0, title: "New-patient offer", content: "Local ad for a specific service (check-up, whitening, consult). Compliant claims only, clear next step to book." },
      { channel: "email", kind: "email", day: 0, title: "Time for your check-up", content: "Remind lapsed patients it's been a while. Warm, professional, no scare tactics. One-tap booking link." },
      { channel: "sms", kind: "sms", day: 3, title: "Quick booking nudge", content: "Short reminder with the booking link for those who didn't open the email. Respect the opt-out." },
      { channel: "email", kind: "email", day: 7, title: "What to expect", content: "For enquiries: reassure first-timers — the process, the team, and how to book. Reduce anxiety, build trust." },
    ],
  },
  {
    id: "course-launch",
    name: "Online Course Launch",
    category: "Education",
    description: "Launch an online course to an email list with a value-first runway and an open-cart window.",
    objective: "Convert subscribers into course buyers during a focused launch window.",
    channel: "Email + Organic",
    steps: [
      { channel: "email", kind: "email", day: -4, title: "Free lesson", content: "Give away one genuinely useful lesson or framework. Prove the teaching quality before selling anything." },
      { channel: "organic", kind: "post", day: -2, title: "Behind the course", content: "Share why you built it and who it's for. Invite people to watch for the open date." },
      { channel: "email", kind: "email", day: 0, title: "Enrollment open", content: "Open the course: the transformation, the curriculum, the price, and a guarantee. One buy action." },
      { channel: "email", kind: "email", day: 3, title: "Cart closing", content: "Final call. Restate the outcome, answer the top objection, note the honest deadline. Clear CTA." },
    ],
  },
  {
    id: "salon-spa",
    name: "Beauty Salon / Spa",
    category: "Beauty",
    description: "Fill quiet slots and rebook clients with a seasonal offer and a rebooking flow.",
    objective: "Book appointments now and increase rebooking rate.",
    channel: "Meta + SMS",
    steps: [
      { channel: "meta", kind: "ad", day: 0, title: "Seasonal offer ad", content: "Show the result (before/after where appropriate) and a specific seasonal offer. Local targeting, book-now CTA." },
      { channel: "landing", kind: "landing", day: 0, title: "Book an appointment", content: "Service list, the offer, stylist/therapist credibility, and a booking widget. Capture phone for reminders." },
      { channel: "sms", kind: "sms", day: 1, title: "Appointment reminder", content: "Confirm date/time and add a reschedule link. Reduce no-shows with a friendly heads-up." },
      { channel: "sms", kind: "sms", day: 14, title: "Time to rebook", content: "A well-timed nudge to rebook before they drift. Make it one tap; respect the opt-out." },
    ],
  },
  {
    id: "home-services",
    name: "Home Services (Plumbing / HVAC)",
    category: "Home services",
    description: "Generate local service calls and follow up quotes into booked jobs.",
    objective: "Fill the schedule with local jobs and convert quotes into work.",
    channel: "Google + SMS",
    steps: [
      { channel: "google", kind: "ad", day: 0, title: "Local service ad", content: "Target high-intent local searches (repair, install, emergency). Lead with area served, response time, and a call button." },
      { channel: "landing", kind: "landing", day: 0, title: "Request a quote", content: "Trust signals (licensed, insured, reviews), the services, and a fast quote-request form or click-to-call." },
      { channel: "sms", kind: "sms", day: 0, title: "Quote follow-up", content: "Confirm you received the request and set expectations for the quote. Fast response wins the job." },
      { channel: "sms", kind: "sms", day: 2, title: "Still need it done?", content: "Follow up on an unaccepted quote. Offer to answer questions or schedule. One clear next step." },
    ],
  },
  {
    id: "b2b-leadgen",
    name: "B2B Lead Generation",
    category: "B2B",
    description: "Generate qualified B2B leads with a valuable asset and a booked-meeting follow-up.",
    objective: "Fill the pipeline with qualified meetings from target accounts.",
    channel: "LinkedIn + Email",
    steps: [
      { channel: "linkedin", kind: "ad", day: 0, title: "Lead-gen asset ad", content: "Offer a genuinely useful asset (benchmark, guide, template) to your target role/industry. Specific promise, easy download." },
      { channel: "landing", kind: "landing", day: 0, title: "Gated asset page", content: "Headline = the outcome, 3 bullets on what's inside, a short form (work email + company). No fluff." },
      { channel: "email", kind: "email", day: 1, title: "Deliver + qualify", content: "Send the asset, then ask one qualifying question or offer a relevant next step. Start the conversation." },
      { channel: "email", kind: "email", day: 4, title: "Book a call", content: "Tie the asset to a specific problem you solve and invite a short call. One booking link, clear value." },
    ],
  },
  {
    id: "nonprofit-fundraise",
    name: "Nonprofit Fundraising",
    category: "Nonprofit",
    description: "Run a focused donation campaign around a clear goal and deadline.",
    objective: "Hit a fundraising goal and grow a base of recurring donors.",
    channel: "Email + Social",
    steps: [
      { channel: "email", kind: "email", day: 0, title: "The story + the goal", content: "Lead with one person or one concrete impact, not statistics. State the goal, the deadline, and how a gift helps." },
      { channel: "organic", kind: "post", day: 1, title: "Progress update", content: "Share momentum — amount raised, a supporter shout-out, or a milestone. Make donors feel part of it." },
      { channel: "email", kind: "email", day: 4, title: "What your gift does", content: "Translate specific amounts into specific outcomes. Add a matching or recurring option if available." },
      { channel: "email", kind: "email", day: 6, title: "Final push", content: "Honest deadline reminder with the running total and one clear donate button. Thank everyone regardless." },
    ],
  },
  {
    id: "auto-dealership",
    name: "Automotive Dealership",
    category: "Automotive",
    description: "Drive test-drive bookings for a model or seasonal event and follow up leads.",
    objective: "Book test drives and convert enquiries into showroom visits.",
    channel: "Meta + Email + SMS",
    steps: [
      { channel: "meta", kind: "ad", day: 0, title: "Test-drive ad", content: "Feature the model and a specific reason to act now (event, finance offer). Local targeting, book-a-test-drive CTA." },
      { channel: "landing", kind: "landing", day: 0, title: "Book a test drive", content: "Model highlights, finance snapshot, and a simple booking form with date/time and contact details." },
      { channel: "sms", kind: "sms", day: 1, title: "Test-drive reminder", content: "Confirm the appointment, address, and what to bring (licence). Add a reschedule link." },
      { channel: "email", kind: "email", day: 4, title: "Follow up the visit", content: "Thank them for coming in, answer open questions, and outline the next step (offer, finance, availability)." },
    ],
  },
  {
    id: "financial-advisor",
    name: "Financial Advisor / Insurance",
    category: "Finance",
    description: "Generate consultation bookings with an educational, trust-first approach.",
    objective: "Book qualified financial-review or insurance consultations, compliantly.",
    channel: "Email + LinkedIn",
    steps: [
      { channel: "linkedin", kind: "ad", day: 0, title: "Educational ad", content: "Offer a genuinely useful guide or checklist (retirement, protection, tax). Educational tone, compliant claims, clear opt-in." },
      { channel: "landing", kind: "landing", day: 0, title: "Guide + book a review", content: "Deliver the guide and offer a no-obligation review. Credentials, what to expect, and a booking option." },
      { channel: "email", kind: "email", day: 2, title: "Common mistake", content: "Teach one costly, common mistake and how a review avoids it. Build trust before asking for the meeting." },
      { channel: "email", kind: "email", day: 5, title: "Book your review", content: "Invite a short, no-pressure consultation. Reassure on privacy and no obligation. One booking link." },
    ],
  },
  {
    id: "professional-services",
    name: "Professional Services (Law / Accounting)",
    category: "Professional services",
    description: "Turn a seasonal need or life event into booked consultations for a professional firm.",
    objective: "Generate qualified consultation enquiries around a timely need.",
    channel: "Google + Email",
    steps: [
      { channel: "google", kind: "ad", day: 0, title: "High-intent search ad", content: "Target searches around the specific service and moment (tax deadline, incorporation, dispute). Clear expertise and a consult CTA." },
      { channel: "landing", kind: "landing", day: 0, title: "Service + enquiry form", content: "Explain the service in plain language, show credentials and outcomes, and offer a short enquiry form or call." },
      { channel: "email", kind: "email", day: 1, title: "What happens next", content: "Confirm the enquiry and set expectations — the process, timelines, and fees at a high level. Reduce uncertainty." },
      { channel: "email", kind: "email", day: 4, title: "Deadline reminder", content: "If timely, remind them of the relevant deadline and the cost of waiting. Offer to book the consultation now." },
    ],
  },
  {
    id: "subscription-box",
    name: "Subscription Box",
    category: "Subscription",
    description: "Acquire subscribers and reduce early churn for a recurring box or membership.",
    objective: "Grow subscribers and keep them past the fragile first months.",
    channel: "Meta + Email",
    steps: [
      { channel: "meta", kind: "ad", day: 0, title: "Subscription ad", content: "Show the unboxing and the ongoing value. Lead with what arrives and the feeling, plus any first-box incentive." },
      { channel: "landing", kind: "landing", day: 0, title: "Plan + subscribe", content: "Explain the plans, cancellation ease, and what's in the next box. Simple checkout, reassurance on flexibility." },
      { channel: "email", kind: "email", day: 1, title: "Welcome + first box", content: "Confirm the subscription, set delivery expectations, and build anticipation for the first box." },
      { channel: "email", kind: "email", day: 21, title: "Keep them past month one", content: "Before the first renewal, reinforce the value, tease the next box, and make managing the plan easy. Reduce churn." },
    ],
  },
];
